SERVERURL: "localhost"
SERVERPORT: "8000"
DBHOST: "localhost"
DBUSERNAME: "postgres"
DBPASSWORD: "12345"
DBPORT: "5432"
DBNAME: "db_go_kost"
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/961186062586236958/4-EXW7G7eVjZbqsslxH-sVyEOBqc05xOlJiVKqS5xFk96xb8qjOy9HJV_c_OPqeqx93C"
DISCORD_USERNAME: "Log Api Error"
MYSQLUSER: "root"
MYSQLPASS: "12345678"
MYSQLURL: "127.0.0.1"
MYSQLPORT: "3306"
MYSQLDBNAME: "db_wm"
REDISURL: "127.0.0.1"
REDISPORT: "6379"
REDISPASSWORD: ""
